name: Pre-Deployment Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  pre-deploy-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: TypeScript check
      run: npx tsc --noEmit
    
    - name: ESLint check
      run: npx next lint
      continue-on-error: true  # Don't fail the workflow, but report issues
    
    - name: Build check
      run: npm run build
      
    - name: Report status
      run: |
        echo "Pre-deployment checks completed."
        echo "Please review any warnings or errors in the logs before proceeding with deployment."
